build: off

clone_folder: c:\github.com\fairyhunter13\go-zendesk

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

cache:
  - '%LocalAppData%\go-build'
  - '%GOPATH%\pkg\mod'

stack: go 1.11

install:
  - go mod download

before_test:
  - go vet ./...

test_script:
  - go test ./...
